---
title: "Weather Data Anlysist"
author: "Ridzuan Mohamad"
date: "1/12/2017"
output: html_document
---

## Introduction

## Sypnosis

The analysis is trying to answer the following questions:

1. Across the United States, which types of events are most harmful with respect to population health?
2. Across the United States, which types of events have the greatest economic consequences?

### 1. Download Data

```{R}
zip_url <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2"
zip_filename <- "StormData.csv.bz2"

if(!file.exists(zip_filename)){
    download.file(zip_url, zip_filename, method="curl")
}
```

### 2. Load Data into dataset

```{R}
df0 <- read.csv(zip_filename, header=TRUE, sep=",")
```

The raw data structure consist of `r dim(df0)[1]` row(s) and `r dim(df0)[2]` columns

List of available columns
```{R, echo=FALSE}
# List out column names
names(df0)
```

Check first 5 rows of raw data
```{R}
head(df0)
```

### 3. Data Cleansing

For this analysis only a few columns which are required to answer both questions. So, we create a subset from raw dataset which contains the meaningful variable for this research. The required column are:--

No. | Column     | Description
----|------------|-----------------------------------
1.  | EVTYPE     | Type of event recorded
2.  | FATALITIES | Number of fatalities reported
3.  | INJURIES   | Number of people injured reported
4.  | PROPDMG    | Property damage measurement
5.  | PROPDMGEXP | The exponential for Property Damage
6.  | CROPDMG    | Crop damage measurement
7.  | CROPDMGEXP | The exponential for Crop Damage

```{R, message=FALSE, warning=FALSE}
library(dplyr)

df1 <- select(df0, EVTYPE, FATALITIES, INJURIES, PROPDMG, PROPDMGEXP, CROPDMG, CROPDMGEXP)
```

Check first 5 rows from subset dataset
```{R}
head(df1)
```

In order to get the right value, we must change the property damage and crop damage to it's actual value. The exponential is describe as shown in the table below:--

No. | EXP | Description
----|-----|-----------------------
1   | H   | Hundred (10^2)
2   | K   | Thousand (10^3)
3   | M   | Million (10^6)
4   | B   | Billion (10^9)

### 4. Analysing Data

#### 4.1 Events are most harmful with respect to population health.

```{R}
ds1 <- df1 %>%
    group_by(EVTYPE) %>%
    summarise(health_affected = sum(FATALITIES + INJURIES)) %>%
    arrange(desc(health_affected))

top10 <- ds1[1:10,]
with(top10, barplot(height = health_affected, names.arg = EVTYPE, las = 3))
```

#### 4.2 Events have the greatest economic consequences

```{R}
ds2 <- df1 %>%
    mutate(actual_propdmg = case_when(.$PROPDMGEXP == "H" ~ .$PROPDMG*10^2,
                                      .$PROPDMGEXP == "K" ~ .$PROPDMG*10^3,
                                      .$PROPDMGEXP == "M" ~ .$PROPDMG*10^6,
                                      .$PROPDMGEXP == "B" ~ .$PROPDMG*10^9,
                                      TRUE ~ .$PROPDMG)) %>%
    mutate(actual_cropdmg = case_when(.$CROPDMGEXP == "H" ~ .$CROPDMG*10^2,
                                      .$CROPDMGEXP == "K" ~ .$CROPDMG*10^3,
                                      .$CROPDMGEXP == "M" ~ .$CROPDMG*10^6,
                                      .$CROPDMGEXP == "B" ~ .$CROPDMG*10^9,
                                      TRUE ~ .$CROPDMG)) %>%
    group_by(EVTYPE) %>%
    summarise(total_actual_damage = sum(actual_propdmg + actual_cropdmg)) %>%
    arrange(desc(total_actual_damage))

top10 <- ds2[1:10,]

library(ggplot2)

ggplot(data=top10, aes(EVTYPE, total_actual_damage/10^3, fill=EVTYPE)) +
    geom_bar(stat="identity") +
    guides(fill=FALSE) +
    theme(axis.text.x=element_text(angle=45, hjust=1))
```

## Summary